name: currnecy_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.6
  firebase_core: ^1.5.0
  google_sign_in: ^5.2.3
  another_flushbar: ^1.10.28
  http: ^0.13.4
  charts_flutter: ^0.12.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  cloud_firestore: ^3.1.7
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/

flutter_icons:
  android: true
  ios: true

